config/routes.rb
Rails.application.routes.draw do
 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  Rails.application.routes.default_url_options[:host] = "localhost:8000"
  
  resources :admin
  root "users#index"
  
  namespace :api do
    namespace :v1 do
      get '/room_images' => "room_images#index"
      get '/room_types' => "room_types#index"
      get '/user_types' => "user_types#index"
      get '/user_room_types' => "user_room_types#index"
      get '/user_room_images' => "user_room_images#index"

      get '/user_requirements' => "user_requirements#index"
      post '/user_requirements/new' => "user_requirements#new"
      post '/user_requirements/create' => "user_requirements#create"
      post '/user_requirements' => "user_requirements#create"

      resources :users

      post 'user_token' => 'user_token#create'
      post 'find_user' => 'users#find'
      
      post 'auth/login' => 'authentication#login'

      post 'passwords/forgot', to: 'passwords#forgot'
      get 'passwords/reset', to: 'passwords#reset'
      put 'passwords/update', to: 'passwords#update'
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room_image.rb
class RoomImage < ApplicationRecord
  mount_uploader :name, ImageUploader

  has_many :user_room_images
end

app/models/room_type.rb
class RoomType < ApplicationRecord
 mount_uploader :image, ImageUploader

 has_many :user_room_images
end

app/models/user.rb
class User < ApplicationRecord

  validates :email, presence: true, uniqueness: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :username, presence: true

  validates :password, :presence => true,
                     :length => { minimum: 6 },allow_blank: true
                      has_secure_password :validations => false

  has_many :user_requirements
  accepts_nested_attributes_for :user_requirements, allow_destroy: true



	def generate_password_token!
		self.reset_password_token = generate_token
		self.reset_password_sent_at = Time.now.utc
		save!
	end

	def password_token_valid?
	  (self.reset_password_sent_at + 4.hours) > Time.now.utc
	end

	def reset_password!(password)
		self.reset_password_token = nil
		self.password = password
		save!
	end

	private
	def generate_token
	  SecureRandom.hex(10)
	end

end

app/models/user_requirement.rb
class UserRequirement < ApplicationRecord
	has_many :user_room_images
	has_many :user_room_types

	accepts_nested_attributes_for :user_room_images, allow_destroy: true
	accepts_nested_attributes_for :user_room_types, allow_destroy: true
    belongs_to :user, inverse_of: :user_requirements
end

app/models/user_room_image.rb
class UserRoomImage < ApplicationRecord
	belongs_to :user_requirement, inverse_of: :user_room_images

	belongs_to :room_image
end

app/models/user_room_type.rb
class UserRoomType < ApplicationRecord
	belongs_to :user_requirement, inverse_of: :user_room_types

	belongs_to :room_type
end

app/models/user_type.rb
class UserType < ApplicationRecord
	belongs_to :user
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!
	def index	
      @user_requirements = UserRequirement.all
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
    :admin
  end

  def resource
    @resource ||= Admin.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:admin]
  end
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/room_types_helper.rb
module RoomTypesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/user_types_helper.rb
module UserTypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<div class="container" ><br>
  <nav class="navbar navbar-expand-sm   navbar-light bg-light" style="margin-bottom: 40px;">
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0" style="margin-right: 800px;">
        <li class="nav-item">
          <a class="nav-link">Admin panel <span class="sr-only">(current)</span></a>
        </li>
      </ul>
      <div>
        <a class="btn btn-danger btn-sm" rel="nofollow" data-method="delete" href="/admin/sign_out" style="
    margin-top: 10px;">Logout</a>  
      </div>
    </div>
  </nav>



  <table  class="table table-condensed" >   
    <thead class="thead-light">
    
      <tr> 
        <th>id</th>   
        <th>user name</th> 
        <th>email</th>
     
        <th>Actions</th>
      </tr>   
    </thead>   
    <tbody>  
      <% @user_requirements.each do|d|%>
        <tr>
          <td><%= d.id %></td>
          <td><%= d.user.name %></td>
          <td><%= d.user.email %></td>
         
           
          <td><%= link_to 'View', admin_user_requirement_path(d),:class => 'btn btn-sm btn-success'
                  %>

        </tr>
      <% end %>   
    </tbody>   
  </table>



  <div>
  
    
  </div>
    <div style="float: right">
        <%= will_paginate @user_requirements, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
      </div>
</div>

   

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InteriorApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>


  </head>

  <body>
    <%= yield %>
    
  </body>
</html>